### ISSUE TITLE
@taxonomy filter on boolean key doesn't appear to work

### ISSUE THREAD

**Issue by jkelleher** [getgrav/grav-plugin-relatedpages#1]
Using this (excerpt) relatedpages.yaml:
```
filter:                         # filter a configurable collection of pages to compare
    items:
       @taxonomy: aproject: true            # supports @self, @page, and @taxonomy collections
    order:
        by: date                # order type by default
        dir: desc               # order direction
```
... it doesn't appear to pull back pages with a taxonomy key/value of *aproject: true*.
Related: Using `taxonomy.findTaxonomy({'aproject':true})` works.

**Comment by mahagr** [comment]
Doesn't work because of YAML syntax doesn't support that. Basically it thinks that you have:

    @taxonomy: "aproject: true"

You may use this instead:

    filter:
      items:
        @taxonomy: 
          aproject: true

**Comment by rhukster** [comment]
I think this is resolved, closing
