### ISSUE TITLE
No message in debugger

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav-plugin-relatedpages#15]
Hello Grav Team, 

I'm trying Related Pages on several installations, with no success.
The plugin should output some message in the debugger, but those messsages are not appearing on all my install.
https://github.com/getgrav/grav-plugin-relatedpages/blob/develop/relatedpages.php#L94

Any help appreciated. 

Thanks!

**Comment by paulmassen** [comment]
After a lot of tests on several grav installs, in different environment, it looks like the plugin is not at fault, but none of my workspaces on cloud9 are able to run the plugin. No error message.
I tried with different php versions, with built-in php webserver, with no luck. 

I will keep investigating and report in case it might help some other users.

**Comment by paulmassen** [comment]
Another information in case it can help:
When I change this line:
https://github.com/getgrav/grav-plugin-relatedpages/blob/develop/relatedpages.php#L82
to test for a string such as:
```
 if ($this->related_pages == "false") {
```
The message from  the plugin appears in the debugger, whereas it does not appear when left untouched.

**Comment by OleVik** [comment]
A php.ini diff reveals these differences compared to fairly bog-standard 7.0.7 php.ini:

```
disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off
[Sybase-CT]
; Allow or prevent persistent links.
; http://php.net/sybct.allow-persistent
sybct.allow_persistent = On
; Maximum number of persistent links. -1 means no limit.
; http://php.net/sybct.max-persistent
sybct.max_persistent = -1
; Maximum number of links (persistent + non-persistent). -1 means no limit.
; http://php.net/sybct.max-links
sybct.max_links = -1
; Minimum server message severity to display.
; http://php.net/sybct.min-server-severity
sybct.min_server_severity = 10
; Minimum client message severity to display.
; http://php.net/sybct.min-client-severity
sybct.min_client_severity = 10
http://php.net/session.gc-probability
session.gc_probability = 0
```

**Comment by paulmassen** [comment]
I will post the php logs tomorrow. I tried it on cloud9 running php5.5.9 as well as php7 and none of them displays the message. I tried with different version of grav and admin plugin too. 

I will post the logs tomorrow, but I didnt see anything suspicious iirc. 

Could you guys confirm you see the debugger message on your latest grav/admin ?

**Comment by paulmassen** [comment]
It was this problem actually:
https://github.com/getgrav/grav-plugin-relatedpages/issues/17
