### ISSUE TITLE
Not working with Grav's Admin Panel

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-relatedpages#3]
The plugin RelatedPages can't be configured using the Admin Panel. For example, if we go to the settings page of the plugin (url `/admin/plugins/relatedpages`) and click on *Save*, there's the following error:

> **Validation failed:** limit is not defined in blueprints

My config: Grav v0.9.39, Admin Panel v0.4.2, RelatedPages v1.0.3

**Comment by flaviocopes** [comment]
Now works since https://github.com/getgrav/grav-plugin-relatedpages/commit/3f01614c4e1237a48c83d46bf2985ee93f6730f2
