### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by bobrocke** [getgrav/grav-plugin-relatedpages#4]
I'm getting this in my error logs for a staging server I have running at Site5:

```[Sun Jan 03 15:51:06 2016] [warn] [client 73.182.46.250] mod_fcgid: stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/bobrocke/public_html/stage.bobrockefeller.com/user/plugins/relatedpages/relatedpages.php on line 177, referer: http://stage.bobrockefeller.com/```

Is it something about that plug-in or something about my server setup? I'm not seeing this problem on my local MAMP Pro site, nor to a see the long delay leading up to the timeout.

My Grav installation is all up to date.

**Comment by rhukster** [comment]
Try turning of `content_match: process:` that one is pretty intensive as it compares each page with every other page.

**Comment by bobrocke** [comment]
I ended up disabling the plug-in as it wasn't being used for anything. I also saw some occasions where too much memory was requests and the served threw a fatal error.

Considering that the site only has about 60 pages, would these problems we expected?

**Comment by rhukster** [comment]
With that content_match setting its possible it would have trouble with only 60 pages.  With that set to false it should be fine.
